### ISSUE TITLE
Package does not work in Unity 2020.

### ISSUE THREAD

**Issue by paring-chan** [PassivePicasso/GameImporter#1]
![image](https://user-images.githubusercontent.com/68010770/125059308-22731780-e0e6-11eb-929f-3f2e508ffcb6.png)

**Comment by PassivePicasso** [comment]
Fixed in [Commit 1411bb2](https://github.com/PassivePicasso/GameImporter/commit/1411bb240f0b249d886a7625342bf4425999ea75)
